version: '3.8'

services:
  # Backend PHP Application
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: receipt-app-backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql
    restart: unless-stopped
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: receipt_db
      DB_USERNAME: root
      DB_PASSWORD: ""
    command: >
      sh -c "sleep 10 &&
            php artisan migrate --force &&
            apache2-foreground"
    networks:
      - receipt-network

  # MySQL Database
  mysql:
    image: mysql:latest
    container_name: receipt-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: receipt_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - receipt-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: receipt-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "9001:80"
    networks:
      - receipt-network

  # Frontend React Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: receipt-app-frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://172.16.4.46:8000/api # <- Important : utiliser le nom du service backend
    restart: unless-stopped
    networks:
      - receipt-network

volumes:
  mysql_data:

networks:
  receipt-network:
    driver: bridge
